<a href="https://colab.research.google.com/github/Sivaperiyasamy/ML-_Algorithms/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[1,2,3]
l.append(4)
print(l)
l.remove(2)
print(l)

cardict={
    "brand":"maruthisuzuki",
    "model":"800 ac",
    "year":"2005"
}
print(cardict)
print(cardict.keys())
print(cardict.values())


[1, 2, 3, 4]
[1, 3, 4]
{'brand': 'maruthisuzuki', 'model': '800 ac', 'year': '2005'}
dict_keys(['brand', 'model', 'year'])
dict_values(['maruthisuzuki', '800 ac', '2005'])


In [ ]:
import numpy as np
arr=np.array([[1,2],[2,3],[3,4]])
print(arr.shape)
print(np.shape(arr))

(3, 2)
(3, 2)


In [ ]:
import numpy as np
np.random.random(3)
np.random.randint(3)
np.random.random((4,3,2))
np.random.random((4,3,2))
np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [ ]:
import numpy as np
a=np.linspace(0.,1.,num=5)
print(a)
f=np.arange(1,11,2)
print(f)

[0.   0.25 0.5  0.75 1.  ]
[1 3 5 7 9]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
#print(a[1:2])
print(a[0:3,1])
#print(a([1:3 2:4]))

[2 4 6]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
#b=np.array([3,2,1,0])
b=np.array([0,1,2,3])
print(a[np.arange(4),b])


[ 1  6 11 16]


In [ ]:
a=np.array([1,4,2,7,3,-4,3,6,3,5,8])
print(np.argmax(a))
print(np.argmin(a)) #arg means index
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])

10
5
[ 5  0  2  4  6  8  1  9  7  3 10]
[10  3  7  9  1  8  6  4  2  0  5]
[ 3  7 10]
[10]


In [ ]:
a=np.array(([0],[1]))
b=np.append(a,[[1],[2]])
print(b)
a=np.array([[1,4,2],[7,3,-4]])
print(np.where(a>5))

[0 1 1 2]
(array([1]), array([0]))


In [ ]:
a=np.array([[1,4,2],[7,3,-4],[3,6,3],[5,8,9]])
c=np.sort(a,axis=1,kind="quicksort")#row wise
b=np.sort(a,axis=0,kind="quicksort")#0=coloumn wise
print(c)
print()
print(b)

[[ 1  2  4]
 [-4  3  7]
 [ 3  3  6]
 [ 5  8  9]]

[[ 1  3 -4]
 [ 3  4  2]
 [ 5  6  3]
 [ 7  8  9]]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

z=np.array([7,6,4])
w=np.array([9,8,7])

print(x.dot(y))
print(z.dot(w))
#TRANSPOSE
print(x.T)

[[19 22]
 [43 50]]
139
[[1 3]
 [2 4]]


In [ ]:
#squeeze will remove unnwanted brackets
a=np.array([[[1,4,2,7,3,-4,3,6,3,5,8]]])
w=np.squeeze(a)
print(w)

#broadcasting will add to all the elemenrs in  the array
print(w+1)

#array broad casting
x=np.array([[1,2],[3,4]])+np.array([[1,2],[3,4]])
print(x)



[ 1  4  2  7  3 -4  3  6  3  5  8]
[ 2  5  3  8  4 -3  4  7  4  6  9]
[[2 4]
 [6 8]]


In [ ]:
a=np.array([1,4,2])+np.array([[1],[2],[3]])
print(a)


[[2 5 3]
 [3 6 4]
 [4 7 5]]
